### ISSUE TITLE
Mac OS - self update function could be renamed

### ISSUE THREAD

**Issue by danlangford** [avereon/xenon#80]
The self update function is finally working on MacOS! Thanks for your work on that. I noticed the update functionality runs a process/program called “elevate”

<img width="555" alt="0E79483D-85CB-42DF-9893-494FA52F2059" src="https://user-images.githubusercontent.com/721364/65773081-d3b6e200-e0f8-11e9-9f1d-62ffb4526548.png">

Which may not be intuitive to a user. Especially if they are doing a lot of different things in their machine they might come back around to this one and think “wait what wants access to my machine?” 

I would suggest just calling it Xenon or XenonUpdater so it’s clear to the users what is going on

**Comment by mvsoder** [comment]
The name of the elevate program should now reflect the name of the program requesting it be elevated. In this case it should show as "Xenon" and the text would read "Xenon wants to make changes."
